/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pawcare.view;

import java.sql.SQLException;

/**
 *
 * @author Arulthas
 */
public class DashboardView extends javax.swing.JFrame {

    private final com.pawcare.model.User loggedInUser;

    public DashboardView(com.pawcare.model.User loggedInUser) {
        this.loggedInUser = loggedInUser;
        initComponents();
        lblWelcome.setText("Welcome, " + loggedInUser.getFullName() + " (" + loggedInUser.getRole() + ")");
        loadDashboardStats();
    }
    
    private void loadDashboardStats() {
    try {
        int totalCustomers = new com.pawcare.service.CustomerService().getAllCustomers().size();
        int totalPets = new com.pawcare.service.PetService().getAllPets().size();

        java.util.List<com.pawcare.model.Appointment> allAppointments =
                new com.pawcare.service.AppointmentService().getAllAppointments();
        long todayCount = allAppointments.stream()
                .filter(a -> a.getAppointmentDate().equals(java.time.LocalDate.now()))
                .count();

        double totalRevenue = new com.pawcare.service.PaymentService().getAllPayments()
                .stream()
                .mapToDouble(p -> p.getAmount().doubleValue())
                .sum();

        lblTotalCustomers.setText("Customers: " + totalCustomers);
        lblTotalPets.setText("Pets: " + totalPets);
        lblTodayAppointments.setText("Today's Appointments: " + todayCount);
        lblTotalRevenue.setText(String.format("Total Revenue: Rs%.2f", totalRevenue));

    } catch (SQLException e) {
        lblTotalCustomers.setText("Customers: --");
        lblTotalPets.setText("Pets: --");
        lblTodayAppointments.setText("Today's Appointments: --");
        lblTotalRevenue.setText("Total Revenue: --");
    }
}
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCustomers = new javax.swing.JButton();
        btnPets = new javax.swing.JButton();
        btnServices = new javax.swing.JButton();
        btnAppointments = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnLogut = new javax.swing.JButton();
        btnTreatments = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        lblTodayAppointments = new javax.swing.JLabel();
        lblTotalCustomers = new javax.swing.JLabel();
        lblTotalPets = new javax.swing.JLabel();
        lblTotalRevenue = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PawCare Clinic - Dashboard");

        btnCustomers.setText("Customer Management");
        btnCustomers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCustomers.addActionListener(this::btnCustomersActionPerformed);

        btnPets.setText("Pet Management");
        btnPets.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPets.addActionListener(this::btnPetsActionPerformed);

        btnServices.setText("Service Management");
        btnServices.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnServices.addActionListener(this::btnServicesActionPerformed);

        btnAppointments.setText("Appointment Management");
        btnAppointments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAppointments.addActionListener(this::btnAppointmentsActionPerformed);

        btnReports.setText("Reports");
        btnReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReports.addActionListener(this::btnReportsActionPerformed);

        btnLogut.setText("Logout");
        btnLogut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogut.addActionListener(this::btnLogutActionPerformed);

        btnTreatments.setText("Treatment Management");
        btnTreatments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTreatments.addActionListener(this::btnTreatmentsActionPerformed);

        btnPayments.setText("Payment Management");
        btnPayments.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayments.addActionListener(this::btnPaymentsActionPerformed);

        lblTodayAppointments.setForeground(java.awt.Color.white);
        lblTodayAppointments.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotalCustomers.setForeground(java.awt.Color.white);
        lblTotalCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotalPets.setForeground(java.awt.Color.white);
        lblTotalPets.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblTotalRevenue.setForeground(java.awt.Color.white);
        lblTotalRevenue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblWelcome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblWelcome.setForeground(java.awt.Color.white);
        lblWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTodayAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTotalPets, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPets, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnPayments, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnCustomers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnLogut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAppointments, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(btnServices, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnTreatments, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalPets, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTodayAppointments, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalRevenue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCustomers)
                    .addComponent(btnServices))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAppointments)
                    .addComponent(btnPets))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPayments)
                    .addComponent(btnTreatments))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogut)
                    .addComponent(btnReports))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogutActionPerformed
        this.dispose();
        new com.pawcare.view.LoginView().setVisible(true);
    }//GEN-LAST:event_btnLogutActionPerformed

    private void btnPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetsActionPerformed
         new PetView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPetsActionPerformed

    private void btnCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomersActionPerformed
    new CustomerView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnCustomersActionPerformed

    private void btnServicesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnServicesActionPerformed
    new ServiceView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnServicesActionPerformed

    private void btnAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentsActionPerformed
        new AppointmentView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAppointmentsActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        com.pawcare.util.ReportUtil.showAppointmentReport();
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnTreatmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreatmentsActionPerformed
        new TreatmentView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnTreatmentsActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        new PaymentView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPaymentsActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointments;
    private javax.swing.JButton btnCustomers;
    private javax.swing.JButton btnLogut;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnPets;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnServices;
    private javax.swing.JButton btnTreatments;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTodayAppointments;
    private javax.swing.JLabel lblTotalCustomers;
    private javax.swing.JLabel lblTotalPets;
    private javax.swing.JLabel lblTotalRevenue;
    private javax.swing.JLabel lblWelcome;
    // End of variables declaration//GEN-END:variables
}
