/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.pawcare.view;

import com.pawcare.controller.AppointmentController;
import com.pawcare.controller.PaymentController;
import com.pawcare.model.Payment;
import com.pawcare.model.User;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
/**
 *
 * @author Arulthas
 */
public class PaymentView extends javax.swing.JFrame {
    
    private final PaymentController paymentController = new PaymentController();
    private final AppointmentController appointmentController = new AppointmentController();
    private final User loggedInUser;
    private int selectedPaymentId = 0; // 0 = Add mode
    private final List<Integer> appointmentIdsForCombo = new ArrayList<>();
    private final Map<Integer, String> appointmentLabelsById = new LinkedHashMap<>();
    /**
     * Creates new form PaymentView
     * @param loggedInUser
     */
    public PaymentView(User loggedInUser) {
    this.loggedInUser = loggedInUser;
    initComponents();
    loadAppointmentDropdown();
    loadPaymentTable();
}
    private void loadAppointmentDropdown() {
    try {
        cmbAppointment.removeAllItems();
        appointmentIdsForCombo.clear();
        appointmentLabelsById.clear();

        for (Map<String, Object> row : appointmentController.getAppointmentDetailsList()) {
            int appointmentId = (int) row.get("appointment_id");
            String label = row.get("customer_name") + " - " + row.get("pet_name")
                    + " - " + row.get("appointment_date") + " " + row.get("appointment_time");
            cmbAppointment.addItem(label);
            appointmentIdsForCombo.add(appointmentId);
            appointmentLabelsById.put(appointmentId, label);
        }
    } catch (SQLException ex) {
        showError("Could not load appointments: " + ex.getMessage());
    }
}

private void loadPaymentTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) tblPayments.getModel();
        model.setRowCount(0);

        for (Payment p : paymentController.getAllPayments()) {
            String appointmentLabel = appointmentLabelsById.getOrDefault(
                    p.getAppointmentId(), "Appointment #" + p.getAppointmentId());
            model.addRow(new Object[]{
                p.getPaymentId(),
                appointmentLabel,
                p.getAmount(),
                p.getPaymentMethod(),
                p.getPaymentDate(),
                p.getPaymentStatus()
            });
        }
    } catch (SQLException ex) {
        showError("Could not load payments: " + ex.getMessage());
    }
}

private BigDecimal parseAmount() {
    try {
        return new BigDecimal(txtAmount.getText().trim());
    } catch (NumberFormatException ex) {
        throw new IllegalArgumentException("Amount must be a valid number, e.g. 2500.00");
    }
}

private LocalDate parsePaymentDate() {
    try {
        return LocalDate.parse(txtPaymentDate.getText().trim());
    } catch (DateTimeParseException ex) {
        throw new IllegalArgumentException("Date must be in yyyy-MM-dd format, e.g. 2026-09-20");
    }
}

private void clearForm() {
    if (cmbAppointment.getItemCount() > 0) cmbAppointment.setSelectedIndex(0);
    txtAmount.setText("");
    if (cmbPaymentMethod.getItemCount() > 0) cmbPaymentMethod.setSelectedIndex(0);
    txtPaymentDate.setText("");
    if (cmbPaymentStatus.getItemCount() > 0) cmbPaymentStatus.setSelectedIndex(0);
    selectedPaymentId = 0;
    tblPayments.clearSelection();
    lblMessage.setText("");
}

private void showError(String message) {
    lblMessage.setForeground(Color.RED);
    lblMessage.setText(message);
}

private void showSuccess(String message) {
    lblMessage.setForeground(new Color(0, 128, 0));
    lblMessage.setText(message);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbAppointment = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        cmbPaymentStatus = new javax.swing.JComboBox<>();
        txtPaymentDate = new javax.swing.JTextField();
        cmbPaymentMethod = new javax.swing.JComboBox<>();
        lblMessage = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayments = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Appointment :");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Amount (Rs.) :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Payment Method :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Status :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Payment Date (yyyy-MM-dd) :");

        txtAmount.addActionListener(this::txtAmountActionPerformed);

        cmbPaymentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "Completed", "Failed" }));

        cmbPaymentMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Card", "Bank Transfer", "Online" }));

        lblMessage.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMessage.setForeground(java.awt.Color.white);
        lblMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnAdd.setText("Add");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        btnBack.setText("Back");
        btnBack.addActionListener(this::btnBackActionPerformed);

        tblPayments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Appointment", "Amount", "Method", "Date", "Status"
            }
        ));
        tblPayments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPaymentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPayments);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnUpdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnClear))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBack)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbPaymentMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(cmbPaymentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete)
                            .addComponent(btnBack))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdate)
                            .addComponent(btnClear)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
         try {
        int index = cmbAppointment.getSelectedIndex();
        if (index < 0) {
            showError("Please select an appointment.");
            return;
        }
        int appointmentId = appointmentIdsForCombo.get(index);

        Payment payment = new Payment(
                appointmentId,
                parseAmount(),
                (String) cmbPaymentMethod.getSelectedItem(),
                parsePaymentDate(),
                (String) cmbPaymentStatus.getSelectedItem()
        );
        paymentController.addPayment(payment);
        showSuccess("Payment recorded successfully.");
        clearForm();
        loadPaymentTable();
    } catch (IllegalArgumentException ex) {
        showError(ex.getMessage());
    } catch (SQLException ex) {
        showError("Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (selectedPaymentId == 0) {
        showError("Select a payment from the table first.");
        return;
    }
    try {
        int index = cmbAppointment.getSelectedIndex();
        if (index < 0) {
            showError("Please select an appointment.");
            return;
        }
        int appointmentId = appointmentIdsForCombo.get(index);

        Payment payment = new Payment(
                selectedPaymentId,
                appointmentId,
                parseAmount(),
                (String) cmbPaymentMethod.getSelectedItem(),
                parsePaymentDate(),
                (String) cmbPaymentStatus.getSelectedItem()
        );
        paymentController.updatePayment(payment);
        showSuccess("Payment updated successfully.");
        clearForm();
        loadPaymentTable();
    } catch (IllegalArgumentException ex) {
        showError(ex.getMessage());
    } catch (SQLException ex) {
        showError("Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (selectedPaymentId == 0) {
        showError("Select a payment from the table first.");
        return;
    }
    int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this, "Delete this payment record?", "Confirm Delete",
            javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    try {
        paymentController.deletePayment(selectedPaymentId);
        showSuccess("Payment deleted.");
        clearForm();
        loadPaymentTable();
    } catch (SQLException ex) {
        showError("Database error: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearForm();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new DashboardView(loggedInUser).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tblPaymentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPaymentsMouseClicked
         int row = tblPayments.getSelectedRow();
    if (row == -1) return;

    DefaultTableModel model = (DefaultTableModel) tblPayments.getModel();
    selectedPaymentId = (int) model.getValueAt(row, 0);

    try {
        for (Payment p : paymentController.getAllPayments()) {
            if (p.getPaymentId() == selectedPaymentId) {
                int comboIndex = appointmentIdsForCombo.indexOf(p.getAppointmentId());
                if (comboIndex >= 0) cmbAppointment.setSelectedIndex(comboIndex);

                txtAmount.setText(p.getAmount().toString());
                cmbPaymentMethod.setSelectedItem(p.getPaymentMethod());
                txtPaymentDate.setText(p.getPaymentDate().toString());
                cmbPaymentStatus.setSelectedItem(p.getPaymentStatus());
                break;
            }
        }
        lblMessage.setText("");
    } catch (SQLException ex) {
        showError("Could not load payment: " + ex.getMessage());
    }
    }//GEN-LAST:event_tblPaymentsMouseClicked

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbAppointment;
    private javax.swing.JComboBox<String> cmbPaymentMethod;
    private javax.swing.JComboBox<String> cmbPaymentStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JTable tblPayments;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtPaymentDate;
    // End of variables declaration//GEN-END:variables
}
